### ISSUE TITLE
Service can't start due to wrong path on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by maikknebel** [galaxyproject/ansible-slurm#10]
On Ubuntu 20.04 LTS the slurm-service doesnt start with the error:

```
systemd[1]: slurmctld.service: Can't open PID file /run/slurmctld.pid (yet?) after start: Operation not permitted
```

I found something similar at [Stackoverflow](https://stackoverflow.com/questions/56553665/how-to-fix-slurmd-service-cant-open-pid-file-error-in-slurm). It seems that the PID-Path between the slurm.conf and the service-definition is different, which leads to the crash. By manually changing the path in slurm.conf it starts without problems, but the playbook has a hardcoded paths for the pid.

/etc/slurm-llnl/slurm.conf
```
SlurmdPidFile=/var/run/slurm-llnl/slurmd.pid
```

/lib/systemd/system/slurmctld.service
```
[Service]
PIDFile=/run/slurmctld.pid
```

Edit: The same problem might apply to the slurmd and slurmdbd services, didnt test that yet, but paths are the same.

**Comment by refual** [comment]
Unfortunately the example playbook given in the README is very minimal.
You can adjust `SlurmctldPidFile` and `SlurmdPidFile` to your liking in the playbook like so:

```yaml
---
- name: Slurm all in One
  hosts: all
  roles:
    - galaxyproject.slurm
  vars:
    slurm_config:
      SlurmctldPidFile: /run/slurmctld.pid
      SlurmdPidFile: /run/slurmd.pid
    slurm_roles: ['controller', 'exec']
```

I'm still getting the error message about `systemd` being unable to open the PID file on my Ubuntu 20.04 system, but the service is shown as running and Slurm appears to be working just fine, too.

You can take a look at the [example playbook from my fork](https://github.com/refual/ansible-slurm#example-playbooks) for a more extensive playbook example.
