### ISSUE TITLE
Port-Ranges are converted into strings

### ISSUE THREAD

**Issue by maikknebel** [galaxyproject/ansible-slurm#2]
When i try to set a port-range, it gets converted into a string, which leads to an error in the slurm-deamon while loading the conf.

```
slurm_nodes:
  - name: dockerworker[1-10]
    NodeAddr: 192.168.0.1
    Port: [6818-6828]
    State: UNKNOWN
```

slurm.conf
```
...
NodeName=dockerworker[1-10] NodeAddr=192.168.0.1 Port=[u'6818-6828'] State=UNKNOWN
...
```

Error in slurmctrld
```
ERROR: [../../../src/common/hostlist.c:1735] Invalid range: `u'6818-6828'': Invalid argument
```

**Comment by erasche** [comment]
If you quote it, it should work. E.g.

```yaml
slurm_nodes:
  - name: dockerworker[1-10]
    NodeAddr: 192.168.0.1
    Port: "[6818-6828]"
    State: UNKNOWN
```
