### ISSUE TITLE
Slurm location changed in debian bullseye

### ISSUE THREAD

**Issue by aknijn** [galaxyproject/ansible-slurm#20]
The location of slurm in debian bullseye is no longer /etc/slurm-llnl but /etc/slurm

**Comment by link89** [comment]
A temporary fix is to repalce all `slurm-llnl` to `slurm` in `defaults/main.yml`.

**Comment by natefoo** [comment]
You can also fix this in your `slurmd_config` like so:

```
slurm_config:
  SlurmctldLogFile: /var/log/slurm/slurmctld.log
  SlurmctldPidFile: /run/slurmctld.pid
  StateSaveLocation: /var/lib/slurm/slurmctld
  SlurmdLogFile: /var/log/slurm/slurmd.log
  SlurmdPidFile: /run/slurmd.pid
  SlurmdSpoolDir: /var/lib/slurm/slurmd
```

We need to figure out what version of Ubuntu this changed in as well and then update the role to set the defaults accordingly.
